import type { Config } from 'tailwindcss'
import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{vue,ts,js,tsx,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        'secondary-dim': '#63ef82',
        'on-secondary-container': '#e4ffe1',
        'tertiary-container': '#ebebeb',
        'surface-variant': '#262626',
        'error-container': '#9f0519',
        'on-tertiary-fixed': '#4f5051',
        'on-surface-variant': '#adaaaa',
        'on-secondary': '#005f26',
        'on-tertiary-fixed-variant': '#6c6d6e',
        'primary-dim': '#e51245',
        'primary-container': '#ff7480',
        'surface-container-high': '#20201f',
        'surface-bright': '#2c2c2c',
        outline: '#767575',
        'on-error-container': '#ffa8a3',
        'secondary-fixed': '#72fe8f',
        'on-tertiary': '#5e5f60',
        'on-background': '#ffffff',
        'surface-container-lowest': '#000000',
        'on-secondary-fixed-variant': '#006a2b',
        'primary-fixed': '#ff7480',
        'inverse-on-surface': '#565555',
        'surface-container-low': '#131313',
        'inverse-surface': '#fcf9f8',
        primary: '#ff8c93',
        'on-primary-fixed': '#000000',
        secondary: '#72fe8f',
        'on-primary-container': '#4e0010',
        background: '#0e0e0e',
        'tertiary-dim': '#ebebeb',
        'surface-dim': '#0e0e0e',
        error: '#ff716c',
        'outline-variant': '#484847',
        'surface-container': '#1a1a1a',
        'surface-tint': '#ff8c93',
        'tertiary-fixed-dim': '#f0f1f1',
        'tertiary-fixed': '#ffffff',
        'inverse-primary': '#bf0036',
        'surface-container-highest': '#262626',
        tertiary: '#f9f9f9',
        'secondary-container': '#006e2d',
        'on-surface': '#ffffff',
        'on-error': '#490006',
        surface: '#0e0e0e',
        'on-secondary-fixed': '#004a1c',
        'error-dim': '#d7383b',
        'on-tertiary-container': '#555757',
        'on-primary-fixed-variant': '#600016',
        'secondary-fixed-dim': '#63ef82',
        'on-primary': '#640018',
        'primary-fixed-dim': '#ff586b',
      },
      fontFamily: {
        headline: ['Manrope'],
        body: ['Inter'],
        label: ['Inter'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  plugins: [forms, containerQueries],
} satisfies Config
